### ISSUE TITLE
Does not work when the trigger event of the action is not a commit

### ISSUE THREAD

**Issue by Torwent** [Sniddl/discord-commits#22]
So I have a chain of github action that depend on each other.

I use this on my second file which is triggered with:
```yml
on:   
  workflow_run:
    workflows: ["Compile test"]
    branches: [master]
    types:
      - completed
```

And this doesn't work because of that.
The thing is, I want to use another way of getting my commit message and I can't because it won't even run
