### ISSUE TITLE
Possibility to remove footer from embed

### ISSUE THREAD

**Issue by Greazi-Times** [Sniddl/discord-commits#25]
When you send a embed it adds a footer to it.
The posibility to get that removed would be great.

**Comment by ZebTheWizard** [comment]
Can you post an example?

**Comment by Greazi-Times** [comment]
![image](https://github.com/Sniddl/discord-commits/assets/69437555/8dbaf916-84a5-4f4d-8254-dcca99e38609)

Like the image above on the end is a line that shows signed-off-by:

**Comment by ZebTheWizard** [comment]
Are you following a [standard like this?](https://ec.europa.eu/component-library/v1.15.0/eu/docs/conventions/git/#commit-message-format). I'm not familiar with footers in commit messages.

**Comment by Greazi-Times** [comment]
Its inside of the embed.
And not the message.

**Comment by ZebTheWizard** [comment]
Git does not define footer standards inside the commit message. You can read more about [GitHub payloads here](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#push). 

I won't support [conventional commits specification](https://www.conventionalcommits.org/) until the parsing library fixes the following issues with [git trailers](https://git-scm.com/docs/git-interpret-trailers).
* https://github.com/conventional-changelog/conventional-changelog/issues/773
* https://github.com/conventional-commits/parser/issues/41

**Comment by ZebTheWizard** [comment]
Reopened because I would like to provide developers with partial control over trailing footers. Thinking an option for regular expressions could help omit parts of the commit body.  Similar to https://github.com/Sniddl/discord-commits/issues/26

**Comment by ZebTheWizard** [comment]
This is now possible in version `1.8`. If a footer token like `Signed-off-by` is not recognized by [conventional-commits-parser](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/README.md) then you need to add it to the `note-keywords` parameter. Put each footer token you want to exclude on a new line. Then make sure `include-footer` is set to `false`.

Example:
```yaml
- name: Discord Commits
  uses: Sniddl/discord-commits@v1.8
  with:
    webhook: ${{ secrets.DISCORD_WEBHOOK }}
    template: "avatar-with-link"
    include-extras: true
    include-footer: false
    note-keywords: |
      Signed-off-by
      Co-authored-by
```
